spring.application.name=project

spring.datasource.url=jdbc:postgresql://localhost:5432/jdbcvtu

spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration

spring.jpa.hibernate.ddl-auto=update
logging.level.com.dsjobby.crm=DEBUG

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.port=8084